# Generated by Django 4.1.1 on 2022-09-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_academician_lecture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academician',
            name='lecture',
        ),
        migrations.AddField(
            model_name='academician',
            name='lecture',
            field=models.ManyToManyField(to='main.lecture'),
        ),
    ]
