# Generated by Django 4.1.1 on 2022-09-28 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_academician_lecture_academician_lecture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academician',
            name='lecture',
        ),
    ]
