# Generated by Django 4.1.1 on 2022-09-28 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_academician_lecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='academician',
            field=models.ManyToManyField(to='main.academician'),
        ),
    ]
