# Generated by Django 4.1.1 on 2022-10-01 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_comment_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 - Very Bad'), (2, '2 - Bad'), (3, '3 - Neutral'), (4, '4 - Good'), (5, '5 - Very Good')], null=True),
        ),
    ]
